package FitnessApp.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import FitnessApp.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.08 20:27:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KayttajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa39 */
  @Test
  public void testLisaa39() {    // Kayttajat: 39
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja eka = new Kayttaja(); 
    Kayttaja toka = new Kayttaja(); 
    assertEquals("From: Kayttajat line: 44", 0, kayttajat.getLkm()); 
    eka.rekisteroi(); 
    kayttajat.lisaa(eka); 
    assertEquals("From: Kayttajat line: 47", 1, kayttajat.getLkm()); 
    toka.rekisteroi(); 
    kayttajat.lisaa(toka); 
    assertEquals("From: Kayttajat line: 50", 2, kayttajat.getLkm()); 
    eka.rekisteroi(); 
    kayttajat.lisaa(eka); 
    assertEquals("From: Kayttajat line: 53", 3, kayttajat.getLkm()); 
    assertEquals("From: Kayttajat line: 54", eka, kayttajat.anna(0)); 
    assertEquals("From: Kayttajat line: 55", toka, kayttajat.anna(1)); 
    assertEquals("From: Kayttajat line: 56", eka, kayttajat.anna(2)); 
    assertEquals("From: Kayttajat line: 57", false, kayttajat.anna(1) == eka); 
    assertEquals("From: Kayttajat line: 58", true, kayttajat.anna(1) == toka); 
  } // Generated by ComTest END
}