package FitnessApp.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import FitnessApp.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.08 20:03:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikkeetTest {



  // Generated by ComTest BEGIN
  /** testLisaa26 */
  @Test
  public void testLisaa26() {    // Liikkeet: 26
    Liikkeet Liikkeet = new Liikkeet(); 
    Liike eka = new Liike(); 
    Liike toka = new Liike(); 
    assertEquals("From: Liikkeet line: 31", 0, Liikkeet.getLkm()); 
    eka.luoLiike(1); 
    Liikkeet.lisaa(eka); 
    assertEquals("From: Liikkeet line: 34", 1, Liikkeet.getLkm()); 
    toka.luoLiike(1); 
    Liikkeet.lisaa(toka); 
    assertEquals("From: Liikkeet line: 37", 2, Liikkeet.getLkm()); 
    eka.luoLiike(1); 
    Liikkeet.lisaa(eka); 
    assertEquals("From: Liikkeet line: 40", 3, Liikkeet.getLkm()); 
    assertEquals("From: Liikkeet line: 41", eka, Liikkeet.anna(0)); 
    assertEquals("From: Liikkeet line: 42", toka, Liikkeet.anna(1)); 
    assertEquals("From: Liikkeet line: 43", eka, Liikkeet.anna(2)); 
    assertEquals("From: Liikkeet line: 44", false, Liikkeet.anna(1) == eka); 
    assertEquals("From: Liikkeet line: 45", true, Liikkeet.anna(1) == toka); 
  } // Generated by ComTest END
}