package FitnessApp.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import java.io.IOException;

import org.junit.*;
import FitnessApp.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.08 19:48:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikeTest {


  // Generated by ComTest BEGIN
  /** testLuoLiike54 */
  @Test
  public void testLuoLiike54() {    // Liike: 54
    Liike testi = new Liike(); 
    testi.luoLiike(); 
    testi.vastaaLiikeNimi("Hauiskääntö"); 
    try {
    testi.tallenna(); 
    } catch (IOException e) {
    e.printStackTrace(); 
    }
    Liike testi1 = new Liike(); 
    testi1.luoLiike(); 
    testi.vastaaLiikeNimi("Hauiskääntö"); 
    try {
    testi1.tallenna(); 
    } catch (IOException e) {
    e.printStackTrace(); 
    }
    int n1 = testi.getLid(); 
    int n2 = testi1.getLid(); 
    assertEquals("From: Liike line: 75", n2-1, n1); 
  } // Generated by ComTest END
}