package FitnessApp.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import java.io.IOException;

import org.junit.*;
import FitnessApp.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.08 18:29:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreeniTest {



  // Generated by ComTest BEGIN
  /** testLuoTreeni71 */
  @Test
  public void testLuoTreeni71() {    // Treeni: 71
    Treeni testi = new Treeni(); 
    testi.luoTreeni(); 
    testi.vastaaAkunTreeni(); 
    try {
		testi.tallenna();
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	} 
    Treeni testi1 = new Treeni(); 
    testi1.luoTreeni(); 
    testi.vastaaAkunTreeni(); 
    try {
		testi1.tallenna();
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	} 
    int n1 = testi.getTid(); 
    int n2 = testi1.getTid(); 
    assertEquals("From: Treeni line: 82", n2-1, n1); 
  } // Generated by ComTest END
}