package FitnessApp.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import FitnessApp.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.08 19:37:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreeniKerratTest {



  // Generated by ComTest BEGIN
  /** testLisaa28 */
  @Test
  public void testLisaa28() {    // TreeniKerrat: 28
    TreeniKerrat treeniKerrat = new TreeniKerrat(); 
    TreeniKerta eka = new TreeniKerta(); 
    TreeniKerta toka = new TreeniKerta(); 
    assertEquals("From: TreeniKerrat line: 33", 0, treeniKerrat.getLkm()); 
    eka.luo(); 
    treeniKerrat.lisaa(eka); 
    assertEquals("From: TreeniKerrat line: 36", 1, treeniKerrat.getLkm()); 
    toka.luo(); 
    treeniKerrat.lisaa(toka); 
    assertEquals("From: TreeniKerrat line: 39", 2, treeniKerrat.getLkm()); 
    eka.luo(); 
    treeniKerrat.lisaa(eka); 
    assertEquals("From: TreeniKerrat line: 42", 3, treeniKerrat.getLkm()); 
    assertEquals("From: TreeniKerrat line: 43", eka, treeniKerrat.anna(0)); 
    assertEquals("From: TreeniKerrat line: 44", toka, treeniKerrat.anna(1)); 
    assertEquals("From: TreeniKerrat line: 45", eka, treeniKerrat.anna(2)); 
    assertEquals("From: TreeniKerrat line: 46", false, treeniKerrat.anna(1) == eka); 
    assertEquals("From: TreeniKerrat line: 47", true, treeniKerrat.anna(1) == toka); 
  } // Generated by ComTest END
}