package FitnessApp.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import java.io.IOException;

import org.junit.*;
import FitnessApp.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.08 19:26:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreeniKertaTest {


  // Generated by ComTest BEGIN
  /** testLuo63 */
  @Test
  public void testLuo63() {    // TreeniKerta: 63
    TreeniKerta testi = new TreeniKerta(); 
    testi.luo(); 
    testi.VastaaMalli(); 
    try {
    testi.tallenna(); 
    } catch (IOException e) {
    e.printStackTrace(); 
    }
    TreeniKerta testi1 = new TreeniKerta(); 
    testi1.luo(); 
    testi1.VastaaMalli(); 
    try {
    testi.tallenna(); 
    } catch (IOException e) {
    e.printStackTrace(); 
    }
    int n1 = testi.getTKID(); 
    int n2 = testi1.getTKID(); 
    assertEquals("From: TreeniKerta line: 84", n2-1, n1); 
  } // Generated by ComTest END
}